version: "3.8"

services:
  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - planner-network
    ports:
      - 5000:5000
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    container_name: postgres
    networks:
      - planner-network
    env_file:
      - .env
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - "pgdata:/var/lib/postgresql/data"

volumes:
  pgdata:

networks:
  planner-network:
    driver: bridge
