version: "3.8"

services:
  postgres:
    image: postgres:14.2
    container_name: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgres/data

  backend:
    container_name: backend
    build:
      context: ./backend/
      dockerfile: Dockerfile.local
    restart: always
    env_file: .env
    volumes:
      - ./backend:/usr/src/app/
    networks:
      - planner-network
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data:

networks:
  planner-network:
