FROM node:14.18-slim

WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

COPY . .

EXPOSE 5000

RUN apt-get -y update
RUN apt-get install -y openssl


CMD ["npm", "run", "start:debug"]